title: "The Fifth Race"
description: "Experiments in co-intelligence and the expansion of human capability."
url: "https://jrmlhermitte.github.io"
baseurl: ""  # keep empty for user.github.io sites

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "mint"

enable_copy_code_button: true

author:
  name: "Julien Lhermitte"
  avatar: "/images/profile.png"
  bio: "Experiments in co-intelligence and the expansion of human capability."
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/jrmlhermitte"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/julien-lhermitte-6374b77"

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter_opts:
    block:
      line_numbers: false

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-spaceship

include:
  - _pages


paginate: 5
paginate_path: "/page:num/"

defaults:
  # All posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
